[openstack_sample_amqp]
type = "AMQPInput"
url = "amqp://<USER>:<PASS>@<RABBIT_ADDRESS>:5673/"
exchange = "ceilometer"
exchange_type = "topic"
exchange_durability = false
exchange_auto_delete = false
queue_auto_delete = false
queue = "metering.sample"
routing_key = "metering.sample"
decoder = "sample_decoder"
splitter = "NullSplitter"
can_exit = false

[sample_decoder]
type = "SandboxDecoder"
filename = "/usr/share/lma_collector/decoders/metering.lua"
module_directory = "/usr/share/lma_collector_modules;/usr/share/heka/lua_modules"

[sample_decoder.config]

    #decode_resources = "TRUE"
    metadata_fields = 'status deleted container_format min_ram updated_at min_disk is_public size checksum created_at disk_format protected instance_host host  display_name instance_id instance_type status state'

[ceilometer_influxdb_accumulator_filter]
type = "SandboxFilter"
filename = "/usr/share/lma_collector/filters/influxdb_accumulator.lua"
preserve_data = false
message_matcher = "Fields[aggregator] == NIL && Type =~ /ceilometer_sample$/"
ticker_interval = 1
module_directory = "/usr/share/lma_collector_modules;/usr/share/heka/lua_modules"

[ceilometer_influxdb_accumulator_filter.config]
    tag_fields = 'deployment_id environment_label hostname tenant_id user_id'
    time_precision = 'ms'
    payload_name = 'sample_data'
    bulk_metric_type_matcher = 'ceilometer_sample$'
    flush_count = 10

[influxdb_encoder]
type = "PayloadEncoder"
append_newlines = false
prefix_ts = false

[samples_influxdb_output]
type = "HttpOutput"
message_matcher = "Fields[payload_type] == 'txt' && Fields[payload_name] == 'sample_data'"
encoder = "influxdb_encoder"
address = "http://10.109.41.14:8086/write?db=ceilometer&precision=ms"
username = "ceilo"
password = "<PASSWORD>"
http_timeout = 5000
method = "POST"

[samples_influxdb_output.headers]
   Content-Type = ["application/x-www-form-urlencoded"]

[elasticsearch_resource_output]
type = "ElasticSearchOutput"
message_matcher = "Type == 'resource'"
encoder = "elasticsearch_resource_encoder"
flush_interval = 5000
flush_count = 10
server = "http://<ES>:9200"

[elasticsearch_resource_encoder]
type = "SandboxEncoder"
filename = "/usr/share/lma_collector/encoders/es_bulk.lua"
module_directory = "/usr/share/lma_collector_modules;/usr/share/heka/lua_modules"

    [elasticsearch_resource_encoder.config]
    index = "ceilometer_resource"
    type_name = "source"

